# Generated by Django 4.0.1 on 2022-01-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglas',
            name='detalji',
            field=models.TextField(null=True),
        ),
    ]
