# Generated by Django 4.0.1 on 2022-01-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_oglas_detalji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_grada', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='oglas',
            name='grad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.grad'),
        ),
    ]
