# Generated by Django 4.0.1 on 2022-01-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_kategorija_ime_kategorije'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oglas',
            name='kategorije',
        ),
        migrations.AddField(
            model_name='oglas',
            name='kategorija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.kategorija'),
        ),
    ]
